### PR TITLE
xpdtools v0.8.2

### PR DESCRIPTION
**Pull request by st3107**
Merge only after success.

This pull request was auto-generated by [rever](https://regro.github.io/rever-docs/)

### CODE REVIEW

**Comment by CJ-Wright** [comment]
please add yourself to the recipe

**Comment by st3107** [comment]
@conda-forge-admin please rerender

**Comment by st3107** [comment]
@conda-forge-admin please rerender

**Comment by st3107** [comment]
@conda-forge-admin please rerender

**Comment by st3107** [comment]
Hi @CJ-Wright . Ready to merge. Thank you.

**Pull request merged**
